name: Render documentation for data

on:
  push:
    branches:
      - gh-workflow

jobs:
  render:
    name: Render Rmarkdown files
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GH_TOKEN }}
      RENV_PATHS_ROOT: ~/.local/share/renv

    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt-get install libcurl4-openssl-dev

      - name: Setup R & Pandoc
        uses: r-lib/actions/setup-r@v1
        with:
          r-version: 'release'
          target_branch: 'gh-workflow'         # Default is gh-pages for github provider
      - uses: r-lib/actions/setup-pandoc@v1

      - name: Cache packages
        uses: actions/cache@v2
        with:
          path: ${{ env.RENV_PATHS_ROOT }}
          key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
          restore-keys: |
            ${{ runner.os }}-renv-

      - name: Restore packages
        run: |
            if (!requireNamespace("renv", quietly = TRUE)) install.packages("renv")
            renv::restore()
        shell: Rscript {0}

      - run: Rscript scripts/generate_docs.R

      - name: Commit results
        run: |
          RMD_PATH= ~./_docs/data
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git commit ${RMD_PATH[*]/.md} -m 'Re-build Rmarkdown files' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
